### 1. 데이터 로딩 및 확인

In [2]:
import pandas as pd

In [ ]:
filename = './data/bccard_201906.csv'
sample_df = pd.read_csv(filename)
sample_df.head(3)

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52

In [6]:
sample_df.tail(3)

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [8]:
len(sample_df), sample_df.shape

(100001, (100001, 24))

### 2. 서울시 거주/비거주 고객 비교 분석

In [ ]:
len(sample_df[sample_df.CSTMR_MEGA_CTY_NM == '서울특별시']) # 서울시 거주 고객 수
len(sample_df[sample_df.CSTMR_MEGA_CTY_NM != '서울특별시']) # 서울시 비거주 고개 수
sample_df[sample_df.CSTMR_MEGA_CTY_NM == '서울특별시']['AMT'].sum() # 서울시 거주 고객 총 소비액
# sample_df.loc[sample_df.CSTMR_MEGA_CTY_NM == '서울특별시', 'AMT'].sum()
sample_df[sample_df.CSTMR_MEGA_CTY_NM != '서울특별시']['AMT'].sum() # 서울시 비거주 고객 총 소비액
sample_df[sample_df.CSTMR_MEGA_CTY_NM == '서울특별시']['CNT'].sum() # 서울시 거주 고객 카드 이용 건수
sample_df[sample_df.CSTMR_MEGA_CTY_NM != '서울특별시']['CNT'].sum() # 서울시 비거주 고객 카드 이용 건수

54150

In [51]:
seoul_dict = {'서울시' : ['거주', '비거주'],
              '고객 수' : [54150, 45851],
              '총 소비액' : [119663142676, 146587135822],
              '카드 이용 건수' : [5542462, 4950200]}
seoul_df = pd.DataFrame(seoul_dict)
seoul_df

   서울시   고객 수         총 소비액  카드 이용 건수
0   거주  54150  119663142676   5542462
1  비거주  45851  146587135822   4950200

### 3. 편의점 소비 정보 분석

In [ ]:
sample_df[sample_df.TP_BUZ_NO == 4010]['AMT'].sum() # 전지역 편의점 소비액

np.int64(7299184098)

In [ ]:
sample_df[sample_df.MEGA_CTY_NM == '서울특별시']['AMT'].sum() # 가맹점 주소 기준 서울시 소비액

np.int64(266250278498)

In [ ]:
sample_df[(sample_df.TP_BUZ_NO == 4010) & (sample_df.CTY_RGN_NM == '강남구')]['AMT'].sum() # 강남구 편의점 소비액

np.int64(707275140)

In [ ]:
sample_df[(sample_df.TP_BUZ_NO == 4010) & (sample_df.CTY_RGN_NM == '강남구') & (sample_df.CSTMR_CTY_RGN_NM == '강남구')]['AMT'].sum() # 강남구 거주자의 강남구 편의점 소비액

np.int64(288379890)

In [ ]:
sample_df[(sample_df.TP_BUZ_NO == 4010) & (sample_df.CTY_RGN_NM == '강남구') & (sample_df.CSTMR_CTY_RGN_NM != '강남구')]['AMT'].sum() # 강남구 비거주자의 강남구 편의점 소비액

np.int64(418895250)

In [ ]:
seoul_con_dict = {'강남구 편의점' : ['거주자', '비거주자'],
                  '소비액' : [288379890, 418895250]}
seoul_con_df = pd.DataFrame(seoul_con_dict)
seoul_con_df

  강남구 편의점        소비액
0     거주자  288379890
1    비거주자  418895250

In [71]:
seoul_con_dict = {'강남구 편의점 총 소비액' : [707275140],
                  '거주자' : [288379890],
                  '비거주자' : [418895250]}
seoul_con_df = pd.DataFrame(seoul_con_dict, index = ['소비액'])
seoul_con_df

     강남구 편의점 총 소비액        거주자       비거주자
소비액      707275140  288379890  418895250